[CDAP-15787] Add failure collector apis
hydrator/file-batch-source-plugins pull request #23
Opened 2019-10-21 23:35 UTC by CuriousVini

2019-10-25 21:23 UTC, mikkin requested changes

2019-10-25 21:23 UTC, mikkin commented on adls-plugins/src/main/java/io/cdap/plugin/sink/ADLSBatchSink.java
> +        collector.addFailure("Output schema must be specified for avro or orc format output files.", null)
nit: Capitalize acronyms

2019-10-25 21:23 UTC, mikkin commented on filesource-common/src/main/java/io/cdap/plugin/common/FileSourceConfig.java
> +      collector.addFailure("Path field can only be used if inputFormatClass is " +
Curious if the `CombinePathTrackingInputFormat.class.getName()` adds a period at the end. Let me know if you have manually verified it.

2019-10-25 23:43 UTC, albertshau commented on adls-plugins/src/main/java/io/cdap/plugin/sink/ADLSBatchSink.java
> +            collector.addFailure("Input schema does not contain the " + fieldName + " field.", null)
enclose field name in single quotes like we do for the other messages.

2019-11-01 20:25 UTC, CuriousVini commented on adls-plugins/src/main/java/io/cdap/plugin/sink/ADLSBatchSink.java
> +        collector.addFailure("Output schema must be specified for avro or orc format output files.", null)
this is how we display it on UI

2019-12-11 23:33 UTC, shifuxu0301 approved these changes
LGTM.

2019-12-11 23:35 UTC, merged